version: '3.4'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'luisquinones-io/test-repo']
    volumes:
        - ".:/plugin:ro"
  md:
    image: tmaier/markdown-spellcheck:latest
    volumes:
      - .:/workdir
