services:
  tests: ...
  spellcheck:
    image: tmaier/markdown-spellcheck:latest
    command: [docker run --rm -ti -v $(pwd):/workdir tmaier/markdown-spellcheck:latest --report "**/*.md"]
    volumes:
      - ".:/workdir"
