name: spellcheck
description: Runs spell checker
author: https://github.com/luisquinones-io
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
