name: test-repo
description: Runs spell checker
author: https://github.com/luisquinones-io
requirements: []
configuration:
  properties:
    readme:
      type: string
    pattern: 
      type: string
  additionalProperties: false
